### ISSUE TITLE
对vuepress-theme-reco的一些疑问

### ISSUE THREAD

**Issue by LCYabaabaaba** [JabinPeng/pengBlog#1]
大佬，我现在初步的在本地开发自己的blog，然后看到你的案例，有些问题能和你交流一下吗，自定义首页，怎么布局这一些问题，想请教一下

**Comment by JabinPeng** [comment]
你加我 qq：690996726




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JabinPeng/pengBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午4:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JabinPeng/pengBlog] 对vuepress-theme-reco的一些疑问 (#1)





 
大佬，我现在初步的在本地开发自己的blog，然后看到你的案例，有些问题能和你交流一下吗，自定义首页，怎么布局这一些问题，想请教一下

**Comment by JabinPeng** [comment]
已解决
