### ISSUE TITLE
关于首页的打字效果的可以出个教程吗

### ISSUE THREAD

**Issue by hkllin** [JabinPeng/pengBlog#10]
关于首页的打字效果的可以出个教程吗

**Comment by hkllin** [comment]
我想问下我在nodemon修改了源码，然后打包不来。。是什么原因

**Comment by JabinPeng** [comment]
vuepress的执行机制 部分代码需要丢到生命周期内执行 在methods里面跑 打包会有问题

**Comment by hkllin** [comment]
好，我晚上回去看看，那我在home组件修改的样式影响吗，还是说只有mtehods里面的影响

**Comment by JabinPeng** [comment]
样式一般没影响 一般部分js跑起来会有影响
