### ISSUE TITLE
启动出现问题

### ISSUE THREAD

**Issue by tangming991** [JabinPeng/pengBlog#4]
node 版本16
![image](https://user-images.githubusercontent.com/62093605/116809861-f893f680-ab72-11eb-95ff-e3e9a6944ba5.png)

**Comment by JabinPeng** [comment]
你没有install吧 依赖都没下载

**Comment by tangming991** [comment]
![image](https://user-images.githubusercontent.com/62093605/116810246-56c1d900-ab75-11eb-88e5-0badd6955dc1.png)

**Comment by JabinPeng** [comment]
在pakejson目录执行这个

**Comment by tangming991** [comment]
谢谢，搞好了，我把node16卸载，转node14然后就可以了。但是还是期待纯vue的前端，我是学习Java后端的，想搞一个自己的博客，那种前后端分离的那样。你的前端界面我认为超级美观

**Comment by JabinPeng** [comment]
好的 希望你早点完成自己心仪的博客
