### ISSUE TITLE
你好，想请教一下边框渐变是怎么应用上去的呀

### ISSUE THREAD

**Issue by Yuiyake** [JabinPeng/pengBlog#6]
在components库里把vue文件写上了，但是怎么让他读取并应用呢？

**Comment by JabinPeng** [comment]
![image](https://user-images.githubusercontent.com/37999218/117523216-2bfad900-afea-11eb-8f9c-048d09b261b8.png)

vuepress 自带机制 ， 可以在markdown 中写组件
