### ISSUE TITLE
可以请教一下大佬，你博客里的总览边框悬浮渐变是怎么做的吗？

### ISSUE THREAD

**Issue by weihuayao** [JabinPeng/pengBlog#7]
rt

**Comment by JabinPeng** [comment]
这有篇文章专门讲这个的哟： 
https://www.zpzpup.com/blog/blogs/category1/2020/20200712.html#_1-%E7%AC%AC%E4%B8%80%E7%A7%8D%E5%8D%95%E5%90%91%E5%8F%98%E8%89%B2

**Comment by bolawen** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JabinPeng/pengBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 上午9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [JabinPeng/pengBlog] 可以请教一下大佬，你博客里的总览边框悬浮渐变是怎么做的吗？ (#7)





 
Closed #7.
 
—我博客有写的&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 在搭建 配置 里面 写的很详细
